    [build]
      publish = "public"          # Netlify に公開する静的ファイル（functions-only サイトにする場合は空でも可）
      functions = "netlify/functions"

    [[headers]]
      for = "/*"
      [headers.values]
        Access-Control-Allow-Origin = "*"
